
source=~/.config/hypr/hyprlock/colors.conf

background {

    monitor =

    path =/home/smtx724/mint/Downloads/363b1bf36e9a25bb79f5de631acaad22.jpg

    blur_passes = 1

    blur_size = 2

    brightness = 0.7

}

label {

    monitor =

    text = $TIME

    color = rgba(ffffffff)

    font_size = 80

    font_family = SF Pro Display Bold

    position = 0, 160

    halign = center

    valign = center

}

label {

    monitor =

    text = cmd[update:5000] date +"%A, %B %d"

    color = rgba(ffffffaa)

    font_size = 18

    font_family = SF Pro Display

    position = 0, 80

    halign = center

    valign = center

}

input-field {

    monitor =

    size = 300, 55

    outline_thickness = 2

    dots_size = 0.25

    dots_spacing = 0.15

    dots_center = true

    outer_color = rgba(e8002dff)

    inner_color = rgba(0a0a0aaa)

    font_color = rgba(ffffffff)

    fade_on_empty = true

    placeholder_text =

    rounding = 28

    position = 0, -60

    halign = center

    valign = center

}

