exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = udiskie &
# exec-once = nwg-dock-hyprland
bind = ALT, A, exec, nwg-drawer
exec-once = mpvpaper -f eDP-1 /home/smtx724/Downloads/musashi.mp4
exec-once = hypr-dock
